name: 'ğŸš€ Packages releases'

on:
  push:
    branches:
      - main

jobs:
  changelog:
    name: 'ğŸš€ Packages releases'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v5
      - name: â­ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 25
          registry-url: 'https://registry.npmjs.org'
      - name: ğŸ”‘ Update npm for Trusted Publishers
        run: npm install -g npm@latest
      - name: ğŸ§° Enable Corepack
        run: corepack enable
      - name: ğŸ“¦ Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: ğŸ”¨ Build packages
        run: yarn build
      - uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
          commit: 'chore: release'
          title: 'Release dashboard'
        env:
          NPM_TOKEN: ''
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}